name: developer_website_software
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.7.0+7

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Call HTTP
  dio: ^5.9.2

  # D.I
  get_it: ^9.2.1
  # State manager
  signals_flutter: ^7.1.0
  dartz: ^0.10.1

  # Cache
  shared_preferences: ^2.5.5

  # Date
  intl: ^0.20.2

  # Infos package
  package_info_plus: ^10.1.0

  # Infos device
  device_info_plus: ^13.1.0

  # Environment variable
  flutter_dotenv: ^6.0.1

  # Macos stuff
  macos_window_utils: ^1.9.1
  window_manager: ^0.5.1

  # Windows stuff
  fluent_ui: ^4.15.1

  # Code generation for model
  json_annotation: ^4.12.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.8

  # Analyze
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linters
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.2.0

  # Code generation
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0

  # Unit test
  mockito: ^5.6.4

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-VariableFont_opsz,wght.ttf
        - asset: fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
